/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BasicTable {
        "tableData": any;
        "tableHeader": any;
    }
    interface MyComponent {
        "columnHeader": { label: string; key: string; }[];
        "data": { name: string; age: number; id: number; }[];
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLBasicTableElement extends Components.BasicTable, HTMLStencilElement {
    }
    var HTMLBasicTableElement: {
        prototype: HTMLBasicTableElement;
        new (): HTMLBasicTableElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "basic-table": HTMLBasicTableElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface BasicTable {
        "tableData"?: any;
        "tableHeader"?: any;
    }
    interface MyComponent {
        "columnHeader"?: { label: string; key: string; }[];
        "data"?: { name: string; age: number; id: number; }[];
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "basic-table": BasicTable;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "basic-table": LocalJSX.BasicTable & JSXBase.HTMLAttributes<HTMLBasicTableElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
